kind: ReplicationController
apiVersion: v1
metadata:
  name: concourse3-worker-controller
spec:
  replicas: 6
  selector:
    component: concourse3-worker
  template:
    metadata:
      labels:
        component: concourse3-worker
    spec:
      volumes:
      - name: workdir
        emptyDir: {}
      containers:
        - name: concourse3-worker
          volumeMounts:
            - name: workdir
              mountPath: "/concourse-work-dir"
          image: navicore/concourse-docker:3.3.4
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          command:
            # worker needs to run as root to run containers
            #- "/usr/bin/dumb-init"
            - "/usr/local/bin/concourse"
          securityContext:
            privileged: true
          env:
          - name: CONCOURSE_BAGGAGECLAIM_DRIVER
            value: "btrfs"
          - name: CONCOURSE_TSA_HOST
            value: "concourse3-web"
          - name: CONCOURSE_TSA_PUBLIC_KEY
            value: "/opt/concourse/keys/tsa_host_key.pub"
          - name: CONCOURSE_TSA_WORKER_PRIVATE_KEY
            value: "/opt/concourse/keys/worker_key"
          - name: CONCOURSE_WORK_DIR
            value: "/concourse-work-dir"
          args: [
            "worker"
          ]
